redirectsOrigin = "config"
plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "D:\\Antigravity\\Carrier Power System\\dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
base = "D:\\Antigravity\\Carrier Power System\\frontend"

[build.environment]
NODE_VERSION = "20"
VITE_API_URL = "https://carrier-power-system-api-production-d1d5.up.railway.app/api"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]